on: push
name: Main Workflow
jobs:
  BuildandTestJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: whoan/docker-build-with-cache-action@v4
        with:
          image_name: kevit/helloworldnodejs
          image_tag:  kevit/helloworldnodejs
          dockerfile: ./app/Dockerfile
      - name: Prepare container for Unittests
        run: docker run -d --name helloworldnodejs-unittest kevit/helloworldnodejs
      - name: Run tests
        run: docker exec helloworldnodejs-unittest npm test
      - name: Run integration tests
        run: docker exec kevit/helloworldnodejs npm run-script itest
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
