on: push
name: Main Workflow
jobs:
  BuildandTestJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker image
        run: |
          cd app
          docker build -t helloworldnodejs:latest .
      - name: Show docker images
        run: docker images -a
      - name: Prepare container for Unittests
        run: docker run helloworldnodejs ls /
      - name: Prepare container for Unittests
        run: docker run helloworldnodejs npm install && npm test
      - name: Run integration tests
        run: docker run helloworldnodejs npm run-script itest
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
